### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by cwichoski** [budo385/todo_bloc_app#2]
Compiler message:
file:///home/clovis/workspace/opensource/flutter/todo_bloc_app/bloc/lib/src/repository/preferences/preferences_interface.dart:5:4: Error: Getter not found: 'protected'.
  @protected
   ^^^^^^^^^
file:///home/clovis/workspace/opensource/flutter/todo_bloc_app/bloc/lib/src/repository/preferences/preferences_interface.dart:5:4: Error: This can't be used as metadata; metadata should be a reference to a compile-time constant variable, or a call to a constant constructor.
  @protected
   ^
Compiler failed on /home/clovis/workspace/opensource/flutter/todo_bloc_app/todo_app_flutter/lib/main.dart
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by blackbeario** [comment]
Make sure to run `flutter packages get` in the flutter directory and `pub get` in the bloc and angular directories.

Some instructions in the README would be super helpful.

**Comment by budo385** [comment]
@cwichoski fixed
