### ISSUE TITLE
Error: FIRAuthErrorDomain

### ISSUE THREAD

**Issue by blackbeario** [budo385/todo_bloc_app#3]
The creds for login: test/test123 don't seem to work in Flutter. The dialog returns a FIRAuthErrorDomain error. However, the AngularDart side works fine (although I thought my computer might explode trying to build).

```PlatformException (PlatformException(Error 17011, FIRAuthErrorDomain, There is no user record corresponding to this identifier. The user may have been deleted.))```

I have tried to use my own Firestore project with my own user email and password, yet I still get the error. Any direction would be greatly appreciated. This bloc example is one of very few repos I can find, so it would be great to actually see it work.

**Comment by budo385** [comment]
Strange, could not reproduce it. Could you give some more info, ios, android?

**Comment by blackbeario** [comment]
@budo385 for me this is on iOS. I have not tried an Android build. Interestingly I found the Firebase connection details quite easily in the Android directory, but have not been able to in iOS. I added my own Google.plist file in the iOS Runner but I'm still getting the error. Thank you for responding and for the repo.

**Comment by budo385** [comment]
@blackbeario pushed the changes, please try now

**Comment by blackbeario** [comment]
Thank you @budo385! The build completes and using the aforementioned creds on iOS works. I tried to copy the details out of your Android google-services.json and into an iOS GoogleService-Info.plist file manually, but it failed. So thank you for taking the time to work this out.

The BLoC pattern is still confusing to me, especially if trying to couple that with Redux. For comparison, I'm hoping to find a repo using Redux w/Firestore in a separate directory that feeds both Flutter and AngularDart.
